Repository fubarnetes/libjail-rs, pull requests merged in 2019-01, with the labels that each got.

#38 refactor: use strum to build param::Types
  Cargo.toml
  src/lib.rs
  src/param.rs
Labels: do-not-merge, enhancement, refactor

#40 iteration: Publish RunningJails as RunningJailIter
  CHANGELOG.md
  src/lib.rs
Labels: enhancement

#41 params: make get_all() return errors
  CHANGELOG.md
  src/param.rs
  src/tests.rs
Labels: bug

#42 RunningJail::from_jid: Check whether jail exists
  CHANGELOG.md
  src/running.rs
  src/stopped.rs
  src/sys.rs
  src/tests.rs
Labels: enhancement

#43 Fix cargo cache in cirrus-ci
  .cirrus.yml
Labels: ci, enhancement

#47 Add coverage scan
  .cirrus.yml
  CHANGELOG.md
Labels: ci, do-not-merge, enhancement
